#define MICROPY_HW_BOARD_NAME "Generic ESP32S2 module"
#define MICROPY_HW_MCU_NAME "ESP32S2"

#define MICROPY_PY_BLUETOOTH (0)
#define MICROPY_HW_ENABLE_SDCARD (0)
#define MICROPY_HW_FLASH_STORAGE_BYTES (0x1F8000)
// Enable UART REPL for modules that have an external USB-UART and don't use native USB.
#define MICROPY_HW_ENABLE_UART_REPL         (0)

#define MICROPY_FATFS_USE_LABEL             (1)

#define MICROPY_THINGZ                      (1)

#define MICROPY_THINGZ_BUTTONS_NB           (2)
#define MICROPY_THINGZ_BUTTONS() { MP_ROM_QSTR(MP_QSTR_button_a),MP_ROM_PTR(&thingz_buttons[0])},{ MP_ROM_QSTR(MP_QSTR_button_b),MP_ROM_PTR(&thingz_buttons[1])}
#define MICROPY_THINGZ_BUTTONS_IOS          {45, 43}
#define MICROPY_THINGZ_TOUCH_BUTTON_NB      (4)

#define MICROPY_THINGZ_TOUCH_BUTTONS_NB     (4)
#define MICROPY_THINGZ_TOUCH_BUTTONS() { MP_ROM_QSTR(MP_QSTR_touch_n),MP_ROM_PTR(&thingz_touch_buttons[0])},{ MP_ROM_QSTR(MP_QSTR_touch_s),MP_ROM_PTR(&thingz_touch_buttons[1])},{ MP_ROM_QSTR(MP_QSTR_touch_e),MP_ROM_PTR(&thingz_touch_buttons[2])},{ MP_ROM_QSTR(MP_QSTR_touch_w),MP_ROM_PTR(&thingz_touch_buttons[3])}
#define MICROPY_THINGZ_TOUCH_BUTTONS_IOS          {8, 4, 5, 9}

#define MICROPY_THINGZ_SCREEN 1
#define MICROPY_THINGZ_SCREEN_WIDTH	160
#define MICROPY_THINGZ_SCREEN_HEIGHT 128
#define MICROPY_THING_SCREEN_BUFF_WIDTH_LEN MICROPY_THINGZ_SCREEN_WIDTH/6
#define MICROPY_THING_SCREEN_BUFF_HEIGHT_LEN MICROPY_THINGZ_SCREEN_HEIGHT/14
#define MICROPY_THINGZ_SCREEN_SCLK_GPIO 12
#define MICROPY_THINGZ_SCREEN_MOSI_GPIO 11
#define MICROPY_THINGZ_SCREEN_TFT_CS_GPIO -1
#define MICROPY_THINGZ_SCREEN_DC_GPIO 44
#define MICROPY_THINGZ_SCREEN_RESET_GPIO 26
#define MICROPY_THINGZ_SCREEN_BL_GPIO -1
#define MICROPY_THINGZ_SCREEN_OFFSETX 0
#define MICROPY_THINGZ_SCREEN_OFFSETY 0

#define MICROPY_THINGZ_I2C 1
#define MICROPY_THINGZ_I2C_SCL 37 
#define MICROPY_THINGZ_I2C_SDA 33
#define MICROPY_THINGZ_I2C_USE_PULLUPS 1

#define MICROPY_THINGZ_ACCEL 1
#define MICROPY_THINGZ_ACCEL_INT_PIN 38
#define MICROPY_THINGZ_ACCEL_INT_PIN2 46
#define MICROPY_THINGZ_ACCEL_LIS2DH12 1

#define MICROPY_THINGZ_MAGNETO 1
#define MICROPY_THINGZ_MAGNETO_QM6310U 1
#define MICROPY_THINGZ_MAGNETO_DRDY -1

#define MICROPY_THINGZ_MEMORY 1

#define MICROPY_THINGZ_LED 1
#define MICROPY_THINGZ_LED_RED 41
#define MICROPY_THINGZ_LED_GREEN 40
#define MICROPY_THINGZ_LED_BLUE 39
#define MICROPY_THINGZ_LED_GND 10

#define MICROPY_THINGZ_SOUND 1
#define MICROPY_THINGZ_SOUND_LEFT 17
#define MICROPY_THINGZ_SOUND_RIGHT 18
#define MICROPY_THINGZ_SOUND_GND 42

#define MICROPY_THINGZ_RADIO 1

#define MICROPY_THINGZ_LOG 1